valor = input('Digite algo: ')
print('O tipo desse valor é: ', type(valor))
print(f'Só tem espaço? {valor.isspace()}')
print(f'É um número? {valor.isnumeric()}')
print(f'É alfabético? {valor.isalpha()}')
print(f'É alfanumérico? {valor.isalnum()}')
print(f'Está em maísculas? {valor.isupper()}')
print(f'Está em minúsculas? {valor.islower()}')
print(f'Está capitalizado? {valor.istitle()}')
